SELECT TITLE FROM MOVIES
WHERE ID IN (SELECT MOVIE_ID FROM STARS WHERE PERSON_ID IN (SELECT ID FROM PEOPLE WHERE NAME LIKE "Johnny Depp" )) AND ID IN (SELECT MOVIE_ID FROM STARS WHERE PERSON_ID IN (SELECT ID FROM PEOPLE WHERE NAME LIKE "Helena Bonham Carter"))
