-- Keep a log of any SQL queries you execute as you solve the mystery.
SELECT  ID , DESCRIPTION FROM CRIME_SCENE_REPORTS
WHERE STREET LIKE "Humphrey Street"
AND MONTH = 7 AND DAY = 28;

SELECT NAME, TRANSCRIPT FROM INTERVIEWS
WHERE DAY = 28
AND MONTH = 7
AND YEAR = 2021;

SELECT ACTIVITY, LICENSE_PLATE, ID FROM BAKERY_SECURITY_LOGS
WHERE YEAR = 2021
AND MONTH = 7
AND DAY = 28
AND HOUR = 10
AND MINUTE = 23;

SELECT ACCOUNT_NUMBER, TRANSACTION_TYPE, AMOUNT, ATM_LOCATION FROM ATM_TRANSACTIONS WHERE YEAR = 2021 AND MONTH = 7 AND DAY = 28 AND ATM_LOCATION LIKE "%Leggett Street%";

SELECT CALLER, RECEIVER, DURATION FROM PHONE_CALLS WHERE YEAR = 2021 AND MONTH = 7 AND DAY = 28 AND DURATION < 60;

SELECT minute, hour, day, destination_airport_id, id FROM FLIGHTS WHERE MONTH = 7 AND YEAR = 2021
AND ID IN (SELECT FLIGHT_ID FROM PASSENGERS WHERE PASSPORT_NUMBER IN (SELECT PASSPORT_NUMBER FROM PEOPLE WHERE LICENSE_PLATE IN
(SELECT LICENSE_PLATE FROM BAKERY_SECURITY_LOGS WHERE YEAR = 2021 AND MONTH = 7 AND DAY = 28 AND HOUR = 10 AND MINUTE = 23)))
AND ID IN (SELECT FLIGHT_ID FROM PASSENGERS WHERE PASSPORT_NUMBER IN (SELECT PASSPORT_NUMBER FROM PEOPLE WHERE PHONE_NUMBER IN
(SELECT CALLER FROM PHONE_CALLS WHERE DAY = 28 AND MONTH = 7 AND YEAR = 2021 AND DURATION < 60)))
AND ID IN (SELECT FLIGHT_ID FROM PASSENGERS WHERE PASSPORT_NUMBER IN (SELECT PASSPORT_NUMBER FROM PEOPLE WHERE ID IN
(SELECT PERSON_ID FROM BANK_ACCOUNTS WHERE ACCOUNT_NUMBER IN (SELECT ACCOUNT_NUMBER FROM ATM_TRANSACTIONS
WHERE YEAR = 2021 AND DAY = 28 AND MONTH = 7 AND ATM_LOCATION LIKE "Leggett Street" AND TRANSACTION_TYPE LIKE "WITHDRAW%"))))
ORDER BY day, hour, minute;

SELECT CITY FROM AIRPORTS
WHERE ID = 4;

SELECT NAME FROM PEOPLE
WHERE PHONE_NUMBER IN (SELECT CALLER FROM PHONE_CALLS WHERE YEAR = 2021 AND MONTH = 7 AND DAY = 28 AND DURATION < 60)
AND PASSPORT_NUMBER IN (SELECT PASSPORT_NUMBER FROM PASSENGERS WHERE FLIGHT_ID IN (SELECT ID FROM FLIGHTS WHERE DESTINATION_AIRPORT_ID = 4 AND ID = 36))
AND LICENSE_PLATE IN (SELECT LICENSE_PLATE FROM BAKERY_SECURITY_LOGS WHERE YEAR = 2021 AND MINUTE < 25 AND MINUTE > 15 AND HOUR = 10 AND MONTH = 7 AND DAY = 28)
AND ID IN (SELECT PERSON_ID FROM BANK_ACCOUNTS WHERE ACCOUNT_NUMBER IN
(SELECT ACCOUNT_NUMBER FROM ATM_TRANSACTIONS WHERE YEAR = 2021 AND MONTH = 7 AND DAY = 28 AND ATM_LOCATION LIKE "%Leggett%Street%" ));

SELECT NAME FROM PEOPLE
WHERE PHONE_NUMBER IN (SELECT RECEIVER FROM PHONE_CALLS WHERE DAY = 28 AND MONTH = 7 AND YEAR = 2021 AND DURATION < 60 AND CALLER IN
(SELECT PHONE_NUMBER FROM PEOPLE WHERE NAME LIKE "Bruce"));




